USE NutritionBuddy;

-- Client sample data (35 rows)
INSERT INTO Client (Name, DOB, Email) VALUES
('James Wilson', '1985-03-12', 'james.wilson@example.com'),
('Emma Davis', '1990-07-25', 'emma.davis@example.com'),
('Michael Johnson', '1978-11-08', 'michael.johnson@example.com'),
('Sophia Martinez', '1992-04-17', 'sophia.martinez@example.com'),
('William Anderson', '1983-09-30', 'william.anderson@example.com'),
('Olivia Thompson', '1995-02-15', 'olivia.thompson@example.com'),
('Noah Garcia', '1975-06-22', 'noah.garcia@example.com'),
('Ava Rodriguez', '1988-12-05', 'ava.rodriguez@example.com'),
('Liam Hernandez', '1991-08-19', 'liam.hernandez@example.com'),
('Charlotte Lewis', '1980-01-29', 'charlotte.lewis@example.com'),
('Benjamin Walker', '1993-05-14', 'benjamin.walker@example.com'),
('Amelia Hall', '1986-10-27', 'amelia.hall@example.com'),
('Elijah Allen', '1979-07-11', 'elijah.allen@example.com'),
('Mia Young', '1994-03-24', 'mia.young@example.com'),
('Lucas King', '1982-12-08', 'lucas.king@example.com'),
('Harper Wright', '1989-09-16', 'harper.wright@example.com'),
('Mason Scott', '1977-04-30', 'mason.scott@example.com'),
('Evelyn Green', '1996-01-13', 'evelyn.green@example.com'),
('Logan Baker', '1984-08-26', 'logan.baker@example.com'),
('Abigail Adams', '1991-05-09', 'abigail.adams@example.com'),
('Jackson Nelson', '1976-11-22', 'jackson.nelson@example.com'),
('Ella Mitchell', '1987-02-06', 'ella.mitchell@example.com'),
('Aiden Roberts', '1993-07-19', 'aiden.roberts@example.com'),
('Sofia Carter', '1980-04-02', 'sofia.carter@example.com'),
('Grayson Phillips', '1990-10-15', 'grayson.phillips@example.com'),
('Scarlett Evans', '1983-06-28', 'scarlett.evans@example.com'),
('Caden Turner', '1979-01-11', 'caden.turner@example.com'),
('Riley Diaz', '1995-11-24', 'riley.diaz@example.com'),
('Julian Reyes', '1981-08-07', 'julian.reyes@example.com'),
('Lily Cooper', '1994-03-21', 'lily.cooper@example.com'),
('Isaiah Reed', '1986-09-04', 'isaiah.reed@example.com'),
('Layla Morgan', '1988-12-17', 'layla.morgan@example.com'),
('David Kelly', '1982-05-30', 'david.kelly@example.com'),
('Zoe Howard', '1997-02-13', 'zoe.howard@example.com'),
('Eli Cox', '1984-07-26', 'eli.cox@example.com');

-- Nutritionist sample data (35 rows)
INSERT INTO Nutritionist (Name, Email) VALUES
('Dr. Sarah Johnson', 'sarah.johnson@nutritionbuddy.com'),
('Dr. Robert Smith', 'robert.smith@nutritionbuddy.com'),
('Alexandra Williams', 'alex.williams@nutritionbuddy.com'),
('Thomas Brown', 'thomas.brown@nutritionbuddy.com'),
('Dr. Emily Davis', 'emily.davis@nutritionbuddy.com'),
('Daniel Miller', 'daniel.miller@nutritionbuddy.com'),
('Sophia Wilson', 'sophia.wilson@nutritionbuddy.com'),
('Dr. David Moore', 'david.moore@nutritionbuddy.com'),
('Olivia Taylor', 'olivia.taylor@nutritionbuddy.com'),
('Dr. Matthew Anderson', 'matthew.anderson@nutritionbuddy.com'),
('Emma Thomas', 'emma.thomas@nutritionbuddy.com'),
('Dr. Christopher Jackson', 'christopher.jackson@nutritionbuddy.com'),
('Isabella White', 'isabella.white@nutritionbuddy.com'),
('Dr. Andrew Harris', 'andrew.harris@nutritionbuddy.com'),
('Ava Martin', 'ava.martin@nutritionbuddy.com'),
('Dr. Joseph Thompson', 'joseph.thompson@nutritionbuddy.com'),
('Mia Garcia', 'mia.garcia@nutritionbuddy.com'),
('Dr. Ryan Martinez', 'ryan.martinez@nutritionbuddy.com'),
('Charlotte Robinson', 'charlotte.robinson@nutritionbuddy.com'),
('Dr. Nicholas Clark', 'nicholas.clark@nutritionbuddy.com'),
('Amelia Rodriguez', 'amelia.rodriguez@nutritionbuddy.com'),
('Dr. Brandon Lewis', 'brandon.lewis@nutritionbuddy.com'),
('Elizabeth Lee', 'elizabeth.lee@nutritionbuddy.com'),
('Dr. Jonathan Walker', 'jonathan.walker@nutritionbuddy.com'),
('Harper Allen', 'harper.allen@nutritionbuddy.com'),
('Dr. Kevin Young', 'kevin.young@nutritionbuddy.com'),
('Abigail King', 'abigail.king@nutritionbuddy.com'),
('Dr. Jason Wright', 'jason.wright@nutritionbuddy.com'),
('Ella Hill', 'ella.hill@nutritionbuddy.com'),
('Dr. Justin Scott', 'justin.scott@nutritionbuddy.com'),
('Sofia Green', 'sofia.green@nutritionbuddy.com'),
('Dr. Brian Baker', 'brian.baker@nutritionbuddy.com'),
('Layla Adams', 'layla.adams@nutritionbuddy.com'),
('Dr. Steven Nelson', 'steven.nelson@nutritionbuddy.com'),
('Zoe Carter', 'zoe.carter@nutritionbuddy.com'); 